import random

def sample_reads_full_coverage(sequence, num_reads=2000, min_len=100, max_len=150):
    seq_len = len(sequence)
    reads = []

    avg_spacing = max(1, (seq_len - max_len) // (num_reads - 1))

    for i in range(num_reads):
        start = i * avg_spacing
        if start > seq_len - max_len:
            start = seq_len - max_len
        read_len = random.randint(min_len, max_len)
        read = sequence[start:start + read_len]
        reads.append((start, read))

    return reads

def reconstruct_from_reads(reads, seq_len):
    print("Sorting reads by start position...")
    reads.sort(key=lambda x: x[0])
    print("Reads sorted.\n")

    reconstructed = [''] * seq_len
    total_reads = len(reads)
    coverage_count = 0

    print("Reconstructing DNA sequence...")
    for idx, (start, read) in enumerate(reads):
        for i, base in enumerate(read):
            pos = start + i
            if pos < seq_len and reconstructed[pos] == '':
                coverage_count += 1
            if pos < seq_len:
                reconstructed[pos] = base
        if (idx+1) % 200 == 0 or idx+1 == total_reads:
            percent = coverage_count / seq_len * 100
            print(f"  Processed {idx+1}/{total_reads} reads — coverage: {percent:.2f}%")
    print("Reconstruction completed.\n")


    for i in range(1, seq_len):
        if reconstructed[i] == '':
            reconstructed[i] = reconstructed[i-1]

    return ''.join(reconstructed)


original = "CGATCCTCCGCTAAGATATTCTTACGTGTAACGTAGCTATGTATTTTACAGAGCTGGCGTACGCGTTGAACACTTCACAGATGATAGGGATTCGGGTAAAGAGCGTGTTATTGGGGACTTACACAGGCGTAGACTACAATGGGCCCAACTCAATCACAGCTCGAGCGCCTTGAATAACGTACTCATCTCTATACATTCTCGACAATCTATCGAGCGACTCGATTATCAACGGGTGTCTTGCAGTTCTAATCTCTTGCCAGCATCGTAATAGCCTCCAAGAGATTGATGATAGTCATGGGCACAGAGCTGAGACGGCGCCGATGGATAGCGGACTTTCGGTCAACCACAATTCCCCACGAGACAGGTCCTGCCGTGCGCATCACTCTGAATGTACAAGCAACCCAAGAGGGCTGAGCCTGGACTCAGCTGGTTCCTGGGTGAGCTCGAGACTCGGGGTGACAGCTCTTCATACATAGAGCGGGGGCGTCGAACGGTCGTGAAAGTCATAGTACCCCGGGTACCAACTTACTGAGGATATTGCTTGAAGCTGTACCGTTTTAGGGGGGGAACGCTGAAGATCTCTTCTTCTCATGACTGAACTCGCGAGGGTCGTGATGTCGGTTCCTTCAAAGGTTAAAGAACAAAGGCTTACTGTGCGCAGAGGAACGCCCATTTAGCGGCTGGCGTCTTGAATCCTCGGTCCCCCTTGTCTTTCCAGATTAATCCATTTCCCTCATTCACGAGCTTACCAAGTCAACATTGGTATATGAATGCGACCTTGAAGAGGCCGCTTAAAAATGGCAGTGGTTGATGCTCTAAACTCCATTTGGTTAACTCGTGTATCACCGCGATAGGCTGATAGAGGTTTAATATTGTATAGCAAGGTACTTCCGGTCTCAATGAATGGCCGGGAAAGGTACGCGCGCGGTATGGGAGGGTCAAGGGGCCAATAGAGAGGCTCCTCTCTCACTCGCTAGGAGGCAATTGTATAACAATGCTTACTGCATCGATACATAAAACGTGTCCATCGGTTGCCCAAACTGTGAAGTGTCTATCACCCCTAGGCCCGTTTCCCGCATATAAACGCCAGGTTGTATCCGCATTTGATGCTACCGTGGATGAGTCAGCGTCGAGCACGCGGCACTTATTGCATGAGTAGGGTTGACTAAGAGCCGTTAGATGCCTCGCTGTACTAATAGTTGTCGACAGATCGTCAAGATTAGAAAACGGTACCAGCATTTTCGGAGGTTCTCTAACTAGTATGGATAGCCGTGTCTTCACTGTGCTGCGGCTACCCATCGCCTGAAATCCAGTTGGTGTCAAGCCATCCCCTGTCCAGGACGCCGCATGTAGTGAAACATACACGTTGCTCGGGTTCACCCCGGTCCGTTCTGAGTCGACCAAGGACACAATCGAGCTCCGATCCGTACTGTCGAGAAACTTGTATCCGACCCCCGCAGCTTGCCAGCTCTTCGGGTATCATGGAGCCTATGGTTGAACGTGTCCGATAACGAACTTCGACATGATAAAGTCCCCCCCTCGCGACTACCAGAGAAGAAGACTACTGAGTTGAGCGTTCCCAGCACTTCAGCCAAGGAAGCTACCAATTTTTAGTTTCCGAGTGTCACGTCTGACCTCGCGGGTAGATTGCCGAGCGTAGAGCTTACGAGCCAGCGGAAACAGTAAGGCCTTTTTAAGTATGGGGAGTAAGTGATCGAACGCTTCAGATGTGACCATATACTTAGGCTGGATCTCGTCCCGTGAATTTTAACCCTCACCAACTACGAGATATGAGGTAAGCCAAAAAAGCACGTGGTGGCGCTCACCGACTGTTCCCAAACTGTAACTCATCGTTCCGTCAAGGCCTGACTTACTTCCCGGCCCTTTCCATGCGCGGACCATACCGTCCTAGTTCTTCGGTTATGTTTCCGATGTAGGAGTGAGCCTACCTCCGTTTGCGTCTTGTTACCAATGAAAAAGCTATGCACTTTGTACAGGGTGCCATCGGGTTTCTGAACTCTCAGATAGTGGGGATCCCGGGAAAGGGCCTATATTTGCGGTCCAACTTAGGCGTAAACCTCGATGCTACCTACTCAGACCCACCCCGCGCGGGGTAAATATGGCACTCATCCCAGCTGGTTCTTGGCGTTCTACGCAGCCACATGTTCATTAACAGTTGTCTGGTAGCACAAAAGTATTACCATGGTCCTAGAAGCCCGGCAGAGTTAGTTCGAACCTAATGCCACAAATGAGACAGGACGCCAATGGGTACCGGACATTAGGTCGAGCTCAGTTCGGTAACGGAGAGACCCTGCGGCGTACTTAATTATGCATATGAAACGCGCCCAAGTGACGCCAGGCAAGTCTCAGCAGGTTCCCGTGTTAGCTCGAGGGTAAACATACAAGCCGATTGAACATGGGTTGGGGGCTTCAAATCGTCGAGGACCCCACAGTACCTCGGAGACCAAGTAGGGCACCCTATAGTTCGAAGCAGAACTAT"
reads = sample_reads_full_coverage(original)
reconstructed = reconstruct_from_reads(reads, len(original))

print("Verification:")
print("Original length:", len(original))
print("Number of reads:", len(reads))
print("Reconstructed length:", len(reconstructed))
print("Reconstruction successful?", reconstructed == original)
